### PR TITLE
Add tutorial for creating a Github release in Go projects

### PR DESCRIPTION
**Pull request by ljvmiranda921**
Reference: #7 
Google Doc: https://docs.google.com/document/d/1QOSZS-QgG0P6QV-0XONNjkfvZ25pXm64tJV_PlzPGew/edit?usp=sharing

### CODE REVIEW

**Comment by ljvmiranda921** [comment]
Hi @bradrydzewski , here's my initial draft of the tutorial. You can review it now. From the contributing docs, it says that we should submit a Google Doc for collaboration, but I think I can start updating the Markdown file. I'm not yet sure where to put that file though, so I created a new file under `golang/github`.

**Comment by bradrydzewski** [comment]
thanks! I will review on Monday (tomorrow) and get back to you right away

**Comment by bradrydzewski** [comment]
@ljvmiranda921 this is really excellent.  I do not have any content-related feedback :)

could you update the pull request to include the markdown?  don't worry about file placement, I can handle this on my end once we merge.

**Comment by ljvmiranda921** [comment]
Hi @bradrydzewski thanks a lot! I will, let me get back to you this weekend!

**Comment by ashwilliams1** [comment]
I hope you don't mind, we converted the Google Doc to a markdown file and pushed to master 😄  Can we use your git email address (lj...@gmail.com) to send you the bounty?  Thanks so much for taking the time to put this together.

**Comment by ljvmiranda921** [comment]
Sure, @ashwilliams1 ! you can use my email for that. Thanks a lot!

**Pull request closed without merging**
